<?php 
	if(!isset($bien_bao_mat)){exit();}
?>
<?php
	if(isset($_POST['bieu_mau_them_menu']))
	{
		include("chuc_nang/menu/them_menu_vao_csdl.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_menu']))
	{
		include("chuc_nang/menu/sua_menu_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_menu']))
	{
		include("chuc_nang/menu/xoa_menu.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_them_nhan_vien']))
	{
		include("chuc_nang/nhan_vien/them_nhan_vien_vao_csdl.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_tt_nhan_vien']))
	{
		include("chuc_nang/nhan_vien/sua_tt_nhan_vien_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_nhan_vien']))
	{
		include("chuc_nang/nhan_vien/xoa_nhan_vien.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_them_khach_hang']))
	{
		include("chuc_nang/khach_hang/them_khach_hang_vao_csdl.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_tt_khach_hang']))
	{
		include("chuc_nang/khach_hang/sua_tt_khach_hang_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_khach_hang']))
	{
		include("chuc_nang/khach_hang/xoa_khach_hang.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_them_san_pham']))
	{
		include("chuc_nang/san_pham/them_san_pham_vao_csdl.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_san_pham']))
	{
		include("chuc_nang/san_pham/sua_san_pham_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_san_pham']))
	{
		include("chuc_nang/san_pham/xoa_san_pham.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_hoa_don']))
	{
		include("chuc_nang/hoa_don/xoa_hoa_don.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_hoa_don_o_trang_chi_tiet']))
	{
		include("chuc_nang/hoa_don/xoa_hoa_don_o_trang_chi_tiet.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_san_pham_trang_chu']))
	{
		include("chuc_nang/san_pham_trang_chu/sua_san_pham_trang_chu.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_san_pham_sale']))
	{
		include("chuc_nang/san_pham_sale/sua_san_pham_sale.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_them_slideshow']))
	{
		include("chuc_nang/slideshow/them_slideshow_vao_csdl.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_slideshow']))
	{
		include("chuc_nang/slideshow/sua_slideshow_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_GET['xoa_slideshow']))
	{
		include("chuc_nang/slideshow/xoa_slideshow.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_banner']))
	{
		include("chuc_nang/banner/sua_banner_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_POST['bieu_mau_sua_footer']))
	{
		include("chuc_nang/footer/sua_footer_o_trong_csdl.php");
		trang_truoc_html();
	}
	if(isset($_GET['thamso']))
	{
		if($_GET['thamso']=="thoat")
		{
			include("chuc_nang/quan_tri_2/thoat.php");
			trang_truoc_html();
		}
	}
?>